ignore:
  - .venv/*
  - venv/*
  - env/*
  - .vscode/*
  - typedllm.egg-info/*
  - "**/tests/*"
  - test_*.py

refactor:
  skip: []

metrics:
  quality_threshold: 25.0

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}
